name: build
run-name: Build
on: [push]
env:
  VERSION: '1.0'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running tests
        run: make -j$(nproc) test
  build-native:
    name: Build (native)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building native
        run: make -j$(nproc)
      - name: Upload native build
        uses: actions/upload-artifact@v3.1.2
        with:
          name: pyra_vol_mon-native
          path: pyra_vol_mon
  build-armhf:
    name: Build (armhf)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install gcc-arm-linux-gnueabihf
        run: sudo apt-get install -y gcc-arm-linux-gnueabihf
      - name: Building with gcc-arm-linux-gnueabihf
        run: make -j$(nproc) CROSS_COMPILE=arm-linux-gnueabihf-
      - name: Upload armhf build
        uses: actions/upload-artifact@v3.1.2
        with:
          name: pyra_vol_mon-armhf
          path: pyra_vol_mon
  build-deb:
    name: Package deb (armhf-generic)
    needs: build-armhf
    runs-on: ubuntu-latest
    steps:
      - name: Download armhf binary
        uses: actions/download-artifact@v3
        with:
          name: pyra_vol_mon-armhf
      - name: Prepare package dir
        run: |
          mkdir -p .debpkg/usr/bin
          mv pyra_vol_mon .debpkg/usr/bin/
          chmod +x .debpkg/usr/bin/pyra_vol_mon
      - name: Create debian package
        id: armhf-deb
        uses: jiro4989/build-deb-action@v2
        with:
          package: pyra-vol-mon
          package_root: .debpkg
          maintainer: Patrik Dahlström <risca@dalakolonin.se>
          version: ${{ env.VERSION }}
          arch: 'armhf'
          depends: 'libc6 (>= 2.2.1)'
          desc: 'This is the Pyra volume monitor.'
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.armhf-deb.outputs.file_name }}
          path: ${{ steps.armhf-deb.outputs.file_name }}
